# Generated by Django 4.2.1 on 2023-05-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discovered_date', models.DateTimeField(verbose_name='date discovered')),
                ('energy', models.IntegerField(default=100)),
                ('metal', models.IntegerField(default=30)),
            ],
        ),
    ]
