# Generated by Django 4.2.1 on 2023-05-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galactic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='energy_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='planet',
            name='metal_level',
            field=models.IntegerField(default=1),
        ),
    ]
