# Generated by Django 4.2.1 on 2023-05-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galactic', '0003_rename_energy_level_planet_metal_mining_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='metal_mining_production',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='planet',
            name='solar_plant_production',
            field=models.IntegerField(default=10),
        ),
    ]
