# Generated by Django 4.2.1 on 2023-05-30 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galactic', '0005_planet_metal_mining_next_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='metal_mining_cost_upgrade_metal',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='planet',
            name='metal_mining_energy_consumption',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='planet',
            name='metal_mining_next_upgrade',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planet',
            name='metal_mining_upgrade_time',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='planet',
            name='solar_plant_cost_upgrade_metal',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='planet',
            name='solar_plant_next_upgrade',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planet',
            name='solar_plant_upgrade_time',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='planet',
            name='metal_mining_next_batch',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 30, 18, 29, 5, 809101, tzinfo=datetime.timezone.utc)),
        ),
    ]
