# Generated by Django 4.2.1 on 2023-06-02 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galactic', '0006_planet_metal_mining_cost_upgrade_metal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='metal_mining_next_batch',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 2, 17, 58, 12, 641145, tzinfo=datetime.timezone.utc)),
        ),
    ]
