# Generated by Django 4.2.1 on 2023-06-02 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galactic', '0007_alter_planet_metal_mining_next_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='robotics_factory_cost_upgrade_metal',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='planet',
            name='robotics_factory_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='planet',
            name='robotics_factory_next_upgrade',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planet',
            name='robotics_factory_upgrade_time',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='planet',
            name='shipyard_dock_cost_upgrade_metal',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='planet',
            name='shipyard_dock_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='planet',
            name='shipyard_dock_next_upgrade',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planet',
            name='shipyard_dock_upgrade_time',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='planet',
            name='metal_mining_next_batch',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 2, 18, 24, 16, 775329, tzinfo=datetime.timezone.utc)),
        ),
    ]
